export const languages = {
  en: {
    accountDeleted: "Your account has been deleted successfully.",
    all: "All",
    allergens: "Allergens",
    askMeLater: "Ask Me Later",
    autoRenewal: "Auto Renewal",
    billingAddress: "Billing Address",
    cancel: "Cancel",
    cancelDeleteAccount: "Cancel Account Deletion",
    cancelDeleteFailed: "Failed to cancel account deletion.",
    cancelDeleteSuccess: "Account deletion cancelled successfully.",
    cancelSubscription: "Cancel Subscription",
    cardHolderName: "Card Holder Name",
    cardHolderNamePlaceholder: "CARD HOLDER NAME",
    cardNumber: "Card Number",
    invalidCardNumber: "Invalid card number",
    categories: "Categories",
    category: "Category",
    changeImage: "Change Image",
    changePlan: "Change Plan",
    choosePlan: "Choose Plan",
    planName: "Subscription Plan",
    viewOtherPlans: "View Other Subscription Plans",
    city: "City",
    close: "Close",
    codeSentAgain: "Verification code has been sent again!",
    confirmCancelSubscription: "Are you sure you want to cancel your subscription?",
    confirmChangePlan: "Are you sure you want to change your plan?",
    confirmChangePlanMessage: "*The selected plan will be active after the end of your current plan.",
    confirmDelete: "Delete Account",
    confirmationDeleteProductMessage: "Do you want to delete this product?",
    confirmationDeleteImageMessage: "Do you want to delete this image?",
    confirmationDeleteMenuImageMessage: "Do you want to delete this menu image?",
    confirmationDeleteMenuMessage: "Do you want to delete this menu?",
    productAvailable: "Available",
    productCreated: "Product created successfully",
    productUpdated: "Product updated successfully",
    productImage: "Product Image",
    productName: "Product Name",
    productNotAvailable: "Not Available",
    country: "Country",
    create: "Create",
    createProduct: "Create Product",
    createCustomCategory: "Create custom category",
    createFailed: "Failed to create product.",
    createMenu: "Create Menu",
    creating: "Creating...",
    currency: "Currency",
    customerInformation: "Customer Information",
    cvc: "CVC",
    cvcPlaceholder: "CVC",
    days: "days",
    planTrial: "TRIAL",
    planMonthly: "MONTHLY",
    planYearly: "YEARLY",
    planFree: "FREE",
    planSmall: "SMALL PLAN",
    planMedium: "MEDIUM PLAN",
    planLarge: "LARGE PLAN",
    monthly: "Monthly",
    yearly: "Yearly",
    currentPlan: "Current Plan",
    nextPlan: "Next Plan",
    planTransition: "Switching to",
    popular: "Popular",
    bestValue: "Best Value",
    businesses: "Businesses",
    employeesPerBusiness: "Employees per business",
    allFeatures: "All Features",
    basicFeatures: "Basic Features",
    digitalMenuAndProducts: "Digital Menu & Products",
    unlimited: "Unlimited",
    upgradeRequired: "Upgrade Required",
    upgradeToAccess: "Upgrade your plan to access this feature",
    upgradePlan: "Upgrade Plan",
    downgradeNotAllowed:
      "Downgrading to a lower paid plan is not supported. To reduce usage, cancel your subscription; you will move to the free plan when the current period ends.",
    notAvailable: "Not available",
    select: "Select",
    businessLimitReached: "You've reached your business limit. Upgrade your plan for more.",
    businessLimitTitle: "Business limit reached.",
    businessLimitMessage: "You can purchase more from the subscription page.",
    employeeLimitReached: "You've reached your employee limit for this business. Upgrade your plan for more.",
    premiumFeature: "Premium Feature",
    moduleRequired: "Module Required",
    purchaseModuleMessage: "You need to purchase this module to access this feature",
    viewSubscriptionPage: "View Subscription Page",
    perMonth: "/month",
    perYear: "/YEAR",
    discount: "Discount",
    deleteAccount: "Delete My Account",
    deleteAccountDescription: "To delete your account, enter the 6-digit code sent to your email address.",
    deleteAccountWait: "Your account is waiting to be deleted until your subscription expires. If you want to reactivate it, please click the button below.",
    deleteFailed: "Failed to delete product.",
    deleteFeedback: "Delete Feedback",
    deleteImageFailed: "Failed to delete image.",
    description: "Product description",
    disabled: "Disabled",
    duration: "Remaining Days",
    editProduct: "Edit Product",
    editMenu: "Edit Menu",
    editMenuProduct: "Edit Menu Product",
    email: "Email",
    enabled: "Enabled",
    endDate: "End Date",
    enterCategoryName: "Enter category name",
    enterProductName: "Enter product name",
    enterDescription: "Enter description",
    enterDiscount: "Enter discount",
    enterInstagramUsername: "Instagram Username",
    enterMenuName: "Enter menu name",
    enterOtpCode: "Enter the 6-digit code sent to your phone",
    enterPrice: "Enter price",
    enterVerificationCode: "Enter 6-digit code",
    error: "Error!",
    success: "Success",
    freePlanBusinessChoiceTitle: "Choose a business for the free plan",
    freePlanBusinessChoiceIntro:
      "You have more than one active business. Select the one you want to keep active on the free plan. The others will be set inactive.",
    freePlanBusinessRetentionWarning:
      "Inactive businesses are kept for about 6 months. After that, their data may be permanently deleted unless you upgrade and reactivate them.",
    freePlanBusinessGraceNote:
      "If you do not choose by the deadline shown below, the oldest business (by creation date) will stay active automatically.",
    freePlanBusinessChoiceSaved: "Your selection has been saved.",
    noBusinessFound: "No businesses found.",
    expireMonth: "MM",
    expireMonthPlaceholder: "MM",
    expireYear: "YYYY",
    expireYearPlaceholder: "YY",
    failedToResendCode: "Failed to send new verification code!",
    failedToSendDeleteAccountEmail: "Failed to send delete account email!",
    failedToSendOtp: "Failed to send OTP code",
    feedback: "Customer Feedback",
    feedbackAndRatings: "Feedback & Ratings",
    feedbackDeleted: "Feedback deleted successfully.",
    tasteRating: "Taste",
    serviceRating: "Service",
    speedRating: "Speed",
    priceRating: "Price",
    overallRating: "Overall Rating",
    totalRatings: "total ratings",
    ratings: "Ratings",
    noRatings: "No ratings yet",
    rateExperience: "Rate your experience",
    writeComment: "Write a comment (optional)",
    atLeastOneRequired: "Please provide at least one rating or comment",
    filter: "Filter",
    forbidden: "Access forbidden. You don't have permission to perform this action.",
    galleryPermissionMessage: "App needs access to your gallery to upload images",
    galleryPermissionTitle: "Gallery Permission",
    generateQrCode: "Generate QR Code",
    getProductsFailed: "Failed to get products.",
    home: "Home",
    imageDeleted: "Image Deleted",
    imageDoesNotExist: "Image does no exist!",
    imageSelectionFailed: "Image selection failed",
    invalidEmail: "Invalid email format!",
    invalidName: "Invalid name format!",
    invalidOtpCode: "Invalid OTP code",
    invalidPlanData: "Invalid plan data",
    invalidPhoneNumber: "Invalid phone number",
    invalidVerificationCode: "Invalid verification code.",
    isAvailable: "Menu Available",
    isCampaign: "Campaign",
    isProductAvailable: "Is Product Available",
    isFavorite: "Favorite",
    isNewItem: "New Item",
    languageSettingsText: "Change Language",
    loading: "Loading...",
    login: "Fast Login",
    loginFailed: "Login failed. Please try again.",
    loginSuccessful: "Login successful!",
    logout: "Logout",
    logoutConfirmation: "Are you sure you want to logout?",
    logoutFailed: "Logout failed. Please try again.",
    logoutSuccessful: "Logout successful!",
    menuProductDoesNotExist: "Menu product does not exist.",
    menuProducts: "Menu Products",
    products: "Products",
    stockManagement: "Stock Management",
    materialStock: "Material Stock",
    productStock: "Product Stock",
    stockSummary: "Stock Summary",
    lowStock: "Low",
    addMaterial: "Add Material",
    editMaterial: "Edit Material",
    materialName: "Material Name",
    enterMaterialName: "Enter material name",
    initialStock: "Initial Stock",
    enterStockAmount: "Enter stock amount",
    materialCreated: "Material created successfully",
    currentStock: "Current Stock",
    addStock: "Add Stock",
    stockUpdated: "Stock updated",
    stockMovements: "Stock Movements",
    stockMovementIn: "Stock In",
    stockMovementOut: "Stock Out",
    stockMovementAdjustment: "Adjustment",
    stockMovementInitialNote: "Initial stock",
    stockMovementAddedNote: "Stock added",
    stockMovementOrderDeduction: "Order deduction: {product}",
    noMovementsFound: "No movements found yet",
    noMaterialsFound: "No materials found",
    createNewMaterial: "Create New Material",
    incompatibleMeasurementUnit: "The usage unit must be compatible with the material stock unit (e.g. kg-g, litre-ml).",
    compatibleUnitsHint: "Stock unit: {unit}. Only compatible units can be selected.",
    noProductStockFound: "No tracked products found",
    stockAlertSettings: "Stock Alert Settings",
    materialThreshold: "Material Alert Threshold (%)",
    productThreshold: "Product Alert Threshold (%)",
    alertEmail: "Alert Email Address",
    alertsActive: "Alerts Active",
    settingsSaved: "Settings saved",
    stockInfo: "Stock Information",
    stockModuleRequired: "Stock Module Required",
    stockModuleRequiredMessage: "Purchase the Stock Management module to use stock features.",
    stockInfoTooltip: "You can set the product quantity and materials used in production here. Stock is automatically deducted when an order is completed.",
    productQuantity: "Product Quantity",
    trackStock: "Track Stock",
    productStockQuantity: "Product quantity (optional)",
    materialInfo: "Material Information",
    selectMaterial: "Select Material",
    notSpecified: "Not specified",
    lastUpdated: "Last updated",
    pieces: "pcs",
    materials: "Materials",
    pleaseCreateMenuFirst: "Please create a menu first.",
    menuDoesNotExist: "Menu does not exist.",
    menuImage: "Business Logo",
    menuLimitError: "You have reached the maximum menu limit",
    menuName: "Menu Name",
    menuCreated: "Menu created successfully",
    menuUpdated: "Menu updated successfully",
    menuNotFound: "Menu not found.",
    menuSubtitle: "There is no menu for this business",
    menuTheme: "Menu Theme",
    name: "Name",
    networkErrorBody: "A network error occurred. Please check your internet connection and try again.",
    networkErrorTitle: "Network Error",
    noInternetConnection: "No internet connection. Please check your connection and try again.",
    connectionTimeout: "The connection timed out. Please check your internet connection and try again.",
    no: "No",
    noFeedbacks: "No feedbacks.",
    noPlansFound: "No plans found. Please check your connection or try again later.",
    noResponse: "No response from server. Please check your internet connection.",
    noResultsFound: "No results found",
    noSubscription: "No subscription found",
    noSubscriptionTitle: "You don't have a subscription yet",
    noSubscriptionMessage: "Choose a plan to unlock all features and start managing your business.",
    explorePlans: "Explore Plans",
    notAdded: "Not Added",
    ok: "OK",
    otpCodeSent: "OTP code sent",
    otpVerification: "OTP Verification",
    passwordRequirements: "Password must be 8-16 characters.",
    permissionDenied: "Permission to save QR code was denied",
    phoneNumber: "Phone Number",
    pleaseAddProduct: "There is no product for this menu",
    pleaseEnterValidPhoneNumber: "Please enter a valid phone number",
    pleaseFillAllFields: "Please fill all required fields",
    price: "Price",
    processing: "Processing...",
    profile: "Profile",
    userName: "User Name",
    businessName: "Business Name",
    enterBusinessName: "Enter business name",
    businessNameTooltip: "This business name will appear on your menus.",
    profileUpdated: "Profile updated successfully",
    completeProfile: "Complete Your Profile",
    welcomeToKuar: "Welcome to Kuar!",
    completeProfileMessage: "Please complete your profile information to get started.",
    enterAddress: "Enter your business address",
    address: "Address",
    emailAlreadyExists: "This email address is already in use",
    qrCode: "QR Code",
    qrCodeSaved: "QR code saved to gallery",
    qrGenerationFailed: "Failed to generate QR code",
    saveFailed: "Failed to save QR code",
    saveToGallery: "Save to Gallery",
    searchByName: "Search by name",
    selectCategory: "Select Category (required)",
    selectMenuTheme: "Select Menu Theme",
    serverError: "Server error occurred. Please try again later.",
    sessionInvalidBody: "Your session has been terminated. Please log in again.",
    sessionInvalidTitle: "Session Terminated",
    settings: "Settings",
    socialMedia: "Instagram Username",
    startDate: "Start Date",
    status: "Status",
    storagePermissionMessage: "App needs access to your storage to upload images",
    storagePermissionTitle: "Storage Permission",
    subscribe: "Buy",
    subscription: "My Subscription",
    subscriptionCancelled: "Subscription cancelled successfully!",
    subscriptionPendingMessage: "Your new plan will become active when your current plan expires.",
    subscriptionCancelledMessage: "*Your subscription will expire and you can purchase a new subscription after that.",
    subscriptionCreated: "Subscription created successfully!",
    subscriptionAlreadyExists: "You already have an active subscription.",
    subscriptionDetails: "Subscription Details",
    subscriptionExpired: "Subscription Ended",
    subscriptionFailed: "Subscription could not be created. Please try again.",
    subscriptionChangeError: "Subscription could not be changed. Please try again.",
    subscriptionPrice: "Subscription Price",
    subscriptionNotFound: "Subscription not found. Please try again.",
    surname: "Surname",
    phone: "Phone Number",
    phonePlaceholder: "+90 5XX XXX XX XX",
    themeSettingsText: "Change Theme",
    tooManyFailedAttempts: "Too many failed attempts. Try again 5 minutes later.",
    trialDescription: "When you select the trial plan, your 7-day trial will start and all your transactions will be free.",
    monthlyDescription: "With the monthly plan, you can use our service by paying every month.",
    yearlyDescription: "With the yearly plan, you can save money by paying once and use our service throughout the year.",
    unableToConnectToServer: "Unable to connect to server. Please check your internet connection.",
    unauthorized: "Unauthorized access. Please log in again.",
    unexpectedErrorOccurred: "An unexpected error occurred. Please try again later.",
    usage: "Usage",
    unsupportedFormat: "The server returned an unsupported format. Please try again.",
    update: "Save",
    save: "Save",
    updateFailed: "Failed to update product.",
    updating: "Saving...",
    uploadFailed: "Failed to upload image.",
    uploadImage: "Upload Image",
    userAccountIsNotActivated: "User account is not activated.",
    userDoesNotExist: "User does not exist!",
    yes: "Yes",
    zipcode: "Zip Code",
    deleteAccountWarning: "To delete your account, enter the OTP code sent to your phone number.",
    resendCode: "Resend Code",
    // Subscription status translations
    statusActive: "ACTIVE",
    statusPending: "PENDING",
    statusCanceled: "CANCELED",
    statusChanged: "CHANGED",
    statusUnpaid: "PAYMENT FAILED",
    statusTrial: "TRIAL",
    statusExpired: "EXPIRED",
    statusFailed: "FAILED",
    type: "Type",
    subscriptionTypeNEW: "New subscription",
    subscriptionTypeUPGRADE: "Upgrade",
    subscriptionTypeDOWNGRADE: "Downgrade",
    retryPayment: "Update Card & Retry Payment",
    retryPaymentDescription: "Enter new card details to retry your failed payment.",
    paymentRetrySuccess: "Payment retried successfully. Your subscription will be activated shortly.",
    cancelPendingChange: "Cancel Plan Change",
    confirmCancelPendingChange: "Are you sure you want to cancel the pending plan change? Your current plan will remain active.",
    pendingChangeCancelled: "Plan change cancelled successfully.",
    paymentDetails: "Payment Details",
    paymentFailed: "Payment failed",
    paymentProcessingMessage: "Completing your payment...",
    paymentProcessingTimeout: "Your payment is being processed. Your subscription will be updated shortly.",
    paymentHistory: "Payment History",
    paymentHistoryDescription: "Your subscription change history.",
    noPaymentHistory: "No payment history found.",
    paymentMethodChoiceTitle: "Payment method",
    useSavedCard: "Use saved card",
    savedCardHint: "Uses the card already stored with our payment provider. No need to re-enter card details.",
    useNewCardInstead: "Use a different card",
    savedPaymentMethodTitle: "Saved payment method",
    savedPaymentMethodDescription: "Your subscription renews with the card stored at our payment provider.",
    updateCardButton: "Update card",
    cardUpdateTitle: "Update card",
    cardUpdateLoadError: "Could not start card update. Please try again.",
    cardUpdateSuccess: "Card updated.",
    cardUpdateOpenedExternally: "The card update page was opened in your browser. Return to the app when you are done.",
    cardInformation: "Card Information",
    addressInformation: "Billing Address",
    billingInfoTitle: "Billing information",
    billingInfoHint: "Used for subscription checkout and invoices.",
    billingInfoUpdated: "Billing information saved",
    zipPostalCode: "Postal / ZIP code",
    menuFooterText: "Made with love in Kocaeli ❤️",
    // Tooltip texts
    menuImageTooltip: "The logo you upload here will appear on your menus.",
    menuNameTooltip: "You can enter the name you want to give to your menu in this field.",
    currencyTooltip: "You can select the currency that will be displayed next to item prices on your menu.",
    menuThemeTooltip: "You can choose from different themes to change the appearance of your menu.",
    instagramTooltip: "The Instagram username you enter here will appear on your menu. Customers can visit your page by tapping it.",
    productImageTooltip: "You can upload your item photo here.",
    productNameTooltip: "You can enter your item name in this field.",
    descriptionTooltip: "You can write a detailed description about your item.",
    categoryTooltip: "You can select which category your item belongs to.",
    allergensTooltip: "You can mark the allergens contained in your item.",
    discountTooltip: "You can enter the discount rate you want to apply to your item (between 0-100).",
    priceTooltip: "You can enter the selling price of your item.",
    // Image Selection Modal
    selectImage: "Select Image",
    selectOrUploadImage: "Select or Upload Image",
    stockImages: "Stock Images",
    gallery: "Gallery",
    searchImages: "Search images... (e.g. pizza, coffee)",
    searchForImages: "Use the search box above to search for images",
    poweredByPixabay: "Free images provided by Pixabay",
    enterSearchQuery: "Please enter a search term",
    noImagesFound: "No images found",
    imageSearchFailed: "Image search failed",
    imageSelected: "Image selected",
    imageDownloadFailed: "Image download failed",
    selectFromGallery: "Click the button below to select an image from your device",
    openGallery: "Open Gallery",
    pixabayCredit: "Free images",
    searchingImages: "Searching for images...",
    info: "Info",
    required: "required",
    optional: "optional",
    // Email/Password Authentication
    loginWithEmail: "Login with Email",
    emailPlaceholder: "Enter your email",
    passwordPlaceholder: "Enter your password",
    confirmPasswordPlaceholder: "Confirm your password",
    noAccountYet: "Don't have an account?",
    signUp: "Sign Up",
    alreadyHaveAccount: "Already have an account?",
    signIn: "Sign In",
    register: "Register",
    registering: "Registering...",
    namePlaceholder: "Enter your name",
    registerSuccess: "Registration successful! Please check your email for activation code.",
    activateAccount: "Activate Account",
    activationCodeSent: "A 6-digit activation code has been sent to your email.",
    enterActivationCode: "Enter 6-digit activation code",
    activating: "Activating...",
    activate: "Activate",
    resendActivationCode: "Resend Activation Code",
    activationSuccess: "Account activated successfully!",
    passwordsDoNotMatch: "Passwords do not match",
    passwordTooShort: "Password must be 8-16 characters",
    invalidEmailFormat: "Please enter a valid email address",
    nameRequired: "Name is required",
    orContinueWith: "or continue with",
    loginWithGoogle: "Sign in with Google",
    loginWithApple: "Sign in with Apple",
    // Suggestion feature
    suggestions: "Suggestions & Feedback",
    suggestionsPlaceholder: "Share your suggestions and feedback with us...",
    submitSuggestion: "Submit",
    suggestionSent: "Thank you! Your suggestion has been sent successfully.",
    suggestionFailed: "Failed to send suggestion. Please try again.",
    enterSuggestion: "Please enter your suggestion",
    // Employee Management
    myEmployees: "My Employees",
    employeeLogin: "Employee Login",
    employeeLoginTitle: "Employee Login",
    accessCode: "Access Code",
    accessCodePlaceholder: "XXXX-XXXX-XXXX",
    invalidAccessCode: "Invalid access code format",
    ownerLogin: "Login as Business Owner",
    addEmployee: "Add Employee",
    editEmployee: "Edit Employee",
    saveChanges: "Save",
    employeeUpdated: "Employee updated. Access code is unchanged.",
    employeeUpdateFailed: "Could not update employee.",
    employeeName: "Employee Name",
    employeePhone: "Phone Number",
    employeeRole: "Role",
    employeeAdded: "Employee added successfully",
    employeeDeleted: "Employee deleted successfully",
    noEmployeesFound: "No employees found. Add your first employee!",
    regenerateCode: "Regenerate Code",
    confirmRegenerateCode: "Are you sure you want to regenerate access code? The old code will no longer work.",
    codeCopied: "New access code",
    deleteEmployee: "Delete Employee",
    confirmDeleteEmployee: "Do you want to delete this employee?",
    roleOwner: "Owner",
    roleManager: "Manager",
    roleWaiter: "Waiter",
    roleChef: "Chef",
    roleCashier: "Cashier",
    selectRole: "Select Role",
    businessLogin: "Business Login",
    employeeLoginInfo: "Ask your employer for the access code to login as an employee.",
    // Table & Order Management
    tableManagement: "Table Management",
    tableAreas: "Table Areas",
    tables: "Tables",
    addArea: "Add Area",
    addTableArea: "Add Area",
    editArea: "Edit Area",
    addTable: "Add Table",
    tableAddModeSingle: "Single",
    tableAddModeBulk: "Bulk",
    tableBulkPrefix: "Prefix",
    tableBulkCount: "Number of tables",
    enterTableBulkPrefix: "e.g. ABC, VIP",
    enterTableBulkCount: "e.g. 10",
    tableBulkInvalidCount: "Enter a whole number of tables between 1 and 100.",
    tableBulkPrefixRequired: "Enter a prefix for table names.",
    tableBulkPreview: "{{p}}-{{start}} … {{p}}-{{end}}",
    tablesBulkCreatedAll: "{{count}} tables created.",
    tablesBulkPartial: "{{ok}} created, {{fail}} failed.",
    areaName: "Area Name",
    tableNumber: "Table Number",
    capacity: "Capacity",
    enterAreaName: "Enter area name",
    enterTableNumber: "e.g. 1, A1, VIP-1",
    table: "Table",
    statusAvailable: "Available",
    statusOccupied: "Occupied",
    statusReserved: "Table reserved",
    statusCleaning: "Cleaning",
    noAreasFound: "No areas found. Add your first area!",
    noTablesFound: "No tables found",
    areaCreated: "Area created successfully",
    areaDeleted: "Area deleted successfully",
    tableCreated: "Table created successfully",
    tableDeleted: "Table deleted successfully",
    confirmDeleteArea: "Delete this area?",
    confirmDeleteTable: "Delete this table?",
    deleteTableFailed: "Could not delete table.",
    deleteAreaFailed: "Could not delete area.",
    editModeHint: "Use the actions under each table. Tap the checkmark when done.",
    areaEditModeHint: "Use the actions under each area. Tap the checkmark when done.",
    tableCardEdit: "Edit",
    tableCardDelete: "Delete",
    editTable: "Edit Table",
    // Orders
    orders: "Orders",
    order: "Order",
    orderNumber: "Order Number",
    noActiveOrder: "No active order",
    noItemsInOrder: "No items in order",
    addProducts: "Add Items",
    addMore: "Add More",
    selectProducts: "Select Items",
    searchProducts: "Search items...",
    noProductsFound: "No items found",
    add: "Add",
    items: "items",
    confirmAndAdd: "Confirm & Add to Order",
    cartEmpty: "Cart is empty",
    itemsAddedToOrder: "Items added to order",
    itemRemoved: "Item removed",
    orderUpdated: "Order updated",
    orderCancelled: "Order cancelled",
    confirmCancelOrder: "Cancel this order?",
    cancelOrderWarning: "This action cannot be undone",
    completeOrder: "Complete",
    waiter: "Waiter",
    total: "Total",
    pending: "Pending",
    preparing: "Preparing",
    ready: "Ready",
    delivered: "Delivered",
    cancelled: "Cancelled",
    deliverSelected: "Deliver",
    deliverOrder: "Deliver order",
    deliverPickQty: "Use + on each row to include ready items in this delivery.",
    deliverPickQtyNoKitchen: "Use + on each row to select quantity to deliver.",
    itemsDelivered: "Delivered",
    // Kitchen Display
    kitchenDisplay: "Kitchen Display",
    activeOrders: "Active Orders",
    pendingItems: "Pending Items",
    noKitchenOrders: "No orders to prepare",
    kitchenRelaxMessage: "Take a break, kitchen is clear!",
    startPreparing: "Start",
    markReady: "Ready",
    itemUpdated: "Item updated",
    // Cashier & Payments
    cashier: "Cashier",
    cash: "Cash",
    creditCard: "Credit Card",
    mealCard: "Meal Card",
    mobilePayment: "Mobile Payment",
    paid: "Paid",
    remaining: "Remaining",
    payAll: "Pay All",
    paySelected: "Pay Selected",
    paymentMethod: "Payment Method",
    paymentCompleted: "Payment completed",
    confirmPayment: "Confirm Payment",
    closeOrder: "Close Order",
    closeFailed: "Failed to close order",
    refundFailed: "Refund failed",
    selectItemsToPay: "Please select items to pay",
    itemSelected: "item(s) selected",
    tableNotAvailableForCashier: "This table cannot be used from cashier right now",
    useReservationModuleForReservations: "Use the Reservations module to manage table reservations.",
    tableOccupiedForReservation: "This table is occupied; reservations apply to available or already reserved tables.",
    reservations: "Reservations",
    reserveTableTitle: "Reserve table",
    reservationNote: "Reservation note",
    reservationNotePlaceholder: "e.g. 7 PM, 4 guests, reservation under Ali Y.",
    reserveTable: "Reserve",
    clearReservation: "Clear reservation",
    updateReservationNote: "Update note",
    reservationNoteRequired: "Please enter a reservation note",
    reservationUpdated: "Reservation saved",
    reservationCleared: "Reservation removed",
    closeOrderConfirmation: "Close this order? Table will be set to available.",
    payBeforeCloseHint: "Collect payment first, then close the bill.",
    goToCashier: "Payment / Close bill",
    selectAll: "Select All",
    confirm: "Confirm",
    fetchFailed: "Failed to fetch data",
    // Business related
    createBusiness: "Create Business",
    businessDescription: "Description",
    businessCreated: "Business created successfully",
    businessUpdated: "Business updated successfully",
    editBusinessTitle: "Edit business",
    businessDeleted: "Business deleted successfully",
    businessDeletionDangerZone: "Danger zone",
    businessDeletionTitle: "Delete business permanently",
    businessDeletionWarning: "This will permanently delete this business and all related data (menus, orders, tables, employees, reports). This cannot be undone.",
    businessDeletionSendCode: "Send verification code to email",
    businessDeletionCodeLabel: "6-digit code from email",
    businessDeletionCodeSent: "Verification code sent to your email.",
    businessDeletionConfirmDelete: "Delete permanently",
    businessDeletionFailed: "Could not complete this action.",
    businessNameRequired: "Business name is required",
    enterBusinessDescription: "Enter description (optional)",
    noBusinesses: "You don't have any businesses yet.",
    createFirstBusiness: "Create your first business to get started.",
    customerFeedback: "Customer Feedback",
    digitalMenu: "Digital Menu",
    noDigitalMenus: "No digital menus yet",
    digitalMenuLimitReached: "A digital menu has already been created for this business. Each business can only create 1 digital menu.",
    // Dashboard & Reports
    dashboard: "Dashboard",
    reports: "Reports",
    revenue: "Revenue",
    totalOrders: "Orders",
    totalItems: "Items Sold",
    averageOrder: "Avg. Order",
    last7Days: "Last 7 Days",
    topProducts: "Top Products",
    paymentDistribution: "Payment Distribution",
    today: "Today",
    thisWeek: "This Week",
    thisMonth: "This Month",
    noReportData: "No data available",
    soldItems: "sold",
    mixed: "Mixed",
    detailedReport: "Detailed Report",
    downloadReport: "Download Report",
    reportDescription: "Detailed HTML report with charts",
    last3Months: "Last 3 Months",
    last6Months: "Last 6 Months",
    shareReport: "Share Report",
    reportReady: "Your Report is Ready",
    reportGenerating: "Generating report...",
    // Permissions
    permissions: "Permissions",
    permissionsDescription: "Select the features this employee can access.",
    permDigitalMenu: "Digital Menu",
    permProducts: "Products",
    permEmployees: "Employees",
    permTableManagement: "Table Management",
    permKitchenDisplay: "Kitchen Screen",
    permCashier: "Cashier",
    permReservation: "Reservations",
    permFeedback: "Customer Feedback",
    permDashboard: "Dashboard",
    defaultPermissions: "Default permissions for this role",
    // Module Subscription
    freeTrialActive: "Free Trial Active",
    dayRemaining: "day remaining",
    daysRemaining: "days remaining",
    recommended: "Recommended",
    basicBundle: "Basic Bundle",
    alreadyOwned: "Already Owned",
    applyBundle: "Apply Bundle",
    owned: "Owned",
    proRated: "Pro-rated",
    yearlyReference: "Annual",
    proRatedForDays: "For remaining {days} days",
    proRatedUntilDate: "Until {date}",
    proRatedForRemainingPeriod: "For the remaining billing period",
    proRatedBillingNote:
      "New modules are priced for the remaining time on your current subscription (until {date}). Strikethrough prices are the full annual rate.",
    proRatedCartNote:
      "Total reflects pro-rated pricing for your current subscription period, not a full year.",
    annualModulePrices: "Prices shown are annual.",
    availableModules: "Available Modules",
    noModulesAvailable: "No modules available.",
    allModulesOwned: "You've unlocked every available module.",
    moduleSelected: "module selected",
    modulesSelected: "modules selected",
    clear: "Clear",
    subtotal: "Subtotal",
    bundleDiscount: "Bundle Discount",
    proceedToPayment: "Proceed to Payment",
    payNow: "Pay Now",
    selectModulesTitle: "Select modules",
    selectModulesMessage: "Please select at least one module to continue.",
    modulesPurchased: "Modules purchased successfully.",
    currentSubscription: "Current Subscription",
    subscriptionEndDate: "End date",
    bundleAlreadyOwned: "Bundle already owned",
    bundleAlreadyOwnedMessage: "You already own all modules in this bundle.",
    fetchError: "Could not load data.",
    businessCount: "Business count",
    free: "Free",
    firstBusinessFree: "1st business free",
    businessLimitReachedModule: "You've reached your business limit. Purchase more from the subscription page.",
    selectBusinessModuleFirst: "Please select the Business module first (1 free business included).",
    subscriptionExpiresTomorrow: "Your subscription expires tomorrow!",
    subscriptionExpiresIn: "Subscription expires in",
    renewToKeepAccess: "Renew to keep access to your modules.",
    trialDaysLeft: "Free trial:",
    trialAllModulesAccess: "You have access to all modules during your trial.",
    emailNotFound: "Email not found",
    // Module names and descriptions
    moduleCreateBusiness: "Create Business",
    moduleCreateBusinessDesc: "Create and manage your business profile",
    moduleDigitalMenu: "Digital Menu",
    moduleDigitalMenuDesc: "Create and manage digital menus with QR codes",
    moduleProductManagement: "Product Management",
    moduleProductManagementDesc: "Manage products, categories, and inventory",
    moduleEmployeeManagement: "Employee Management",
    moduleEmployeeManagementDesc: "Manage employees, roles, and permissions",
    moduleTableManagement: "Table Management",
    moduleTableManagementDesc: "Manage tables, areas, and seating arrangements",
    moduleCashRegister: "Cash Register",
    moduleCashRegisterDesc: "Process payments and manage transactions",
    moduleKitchenDisplay: "Kitchen Display",
    moduleKitchenDisplayDesc: "Kitchen order management and preparation tracking",
    moduleReservations: "Reservations",
    moduleReservationsDesc: "Manage table reservations and bookings",
    moduleFeedback: "Customer Feedback",
    moduleFeedbackDesc: "Collect and manage customer feedback",
    moduleDashboard: "Dashboard",
    moduleDashboardDesc: "View reports, analytics, and business insights",
    bundleBasicName: "Basic Bundle",
    bundleBasicDesc: "Everything you need to get started",
    // Web shell & shared UI
    back: "Back",
    delete: "Delete",
    new: "New",
    theme: "Theme",
    lightMode: "Light",
    darkMode: "Dark",
    selectLanguage: "Select language",
    language: "Language",
    connected: "Live",
    disconnected: "Offline",
    itemReady: "Item ready",
    cancelItem: "Cancel item",
    search: "Search",
    cancelOrder: "Cancel order",
    orderSent: "Order sent",
    sendOrder: "Send order",
    createTable: "Create Tables",
    noOrders: "No active orders",
    business: "Business",
    welcome: "Welcome",
    openMenu: "Open menu",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",
    pageNotFound: "Page not found",
    pageNotFoundDescription:
      "The page you are looking for may have been moved, deleted, or never existed.",
    homePage: "Home",
    goToDashboard: "Go to dashboard",
    noFeedback: "No feedback yet",
    unexpectedErrorTitle: "Something went wrong",
    unexpectedErrorDescription:
      "An unexpected error occurred. Please try again. If the problem persists, contact support.",
    errorCode: "Error code",
    tryAgain: "Try again",
    share: "Share",
    copy: "Copy",
    regenerateAccessCode: "Regenerate code",
    accessCodeRegenerated: "Access code regenerated",
    noEmployees: "No employees yet",
    addItem: "Add item",
    noTablesYet: "No tables yet",
    tablePrefix: "Prefix",
    capacityLabel: "Capacity",
    count: "Count",
    tableStatusEmpty: "Empty",
    tableStatusOccupied: "Occupied",
    tableStatusReserved: "Reserved",
    menu: "Menu",
    password: "Password",
    forgotPassword: "Forgot password?",
    loginSubtitle: "Continue with your business or employee account",
    showPassword: "Show password",
    hidePassword: "Hide password",
    footerTagline:
      "Modern management platform for restaurants and cafés. Digital menu, orders, kitchen, and cashier — all in one place.",
    footerProduct: "Product",
    footerFeatures: "Features",
    footerLegal: "Legal",
    footerPrivacy: "Privacy",
    footerTerms: "Terms of Service",
    footerContact: "Contact",
    footerCopyright: "All rights reserved.",
    footerMadeWith: "Made with love in Kocaeli",
    registerSubtitle: "Start managing your business with Kuar",
  },
  tr: {
    accountDeleted: "Hesabınız başarıyla silindi.",
    all: "Tümü",
    allergens: "Alerjenler",
    askMeLater: "Daha Sonra Sor",
    autoRenewal: "Otomatik Yenileme",
    billingAddress: "Fatura Adresi",
    cancel: "İptal Et",
    cancelDeleteAccount: "Hesap Silmeyi İptal Et",
    cancelDeleteFailed: "Hesap silme iptal edilemedi.",
    cancelDeleteSuccess: "Hesap silme işlemi başarıyla iptal edildi.",
    cancelSubscription: "Aboneliği İptal Et",
    cardHolderName: "Kart Sahibi Adı",
    cardHolderNamePlaceholder: "KART SAHİBİ",
    cardNumber: "Kart Numarası",
    invalidCardNumber: "Kart numarası geçersizdir",
    categories: "Kategoriler",
    category: "Kategori",
    changeImage: "Resmi Değiştir",
    changePlan: "Planı Değiştir",
    choosePlan: "Plan Seçiniz",
    planName: "Abonelik Planı",
    viewOtherPlans: "Diğer Abonelik Planlarını Gör",
    city: "Şehir",
    close: "Kapat",
    codeSentAgain: "Doğrulama kodu tekrar gönderildi!",
    confirmCancelSubscription: "Aboneliğinizi iptal etmek istediğinize emin misiniz?",
    confirmChangePlan: "Seçili pakete geçmek istediğinize emin misiniz?",
    confirmChangePlanMessage: "*Seçtiğiniz paket mevcut paketinizin bitiminde aktif olacaktır.",
    confirmDelete: "Hesabı Sil",
    confirmationDeleteProductMessage: "Bu ürünü silmek istiyor musunuz?",
    confirmationDeleteImageMessage: "Bu resmi silmek istiyor musunuz?",
    confirmationDeleteMenuImageMessage: "Bu menü resmini silmek istiyor musun?",
    confirmationDeleteMenuMessage: "Bu menüyü silmek istiyor musun?",
    productAvailable: "Mevcut",
    productCreated: "Ürün başarıyla oluşturuldu",
    productUpdated: "Ürün başarıyla düzenlendi",
    productImage: "Ürün Resmi",
    productName: "Ürün Adı",
    productNotAvailable: "Mevcut Değil",
    country: "Ülke",
    create: "Oluştur",
    createProduct: "Ürün Oluştur",
    createCustomCategory: "Kendi kategorini oluştur",
    createFailed: "Ürün oluşturulamadı.",
    createMenu: "Menü Oluştur",
    creating: "Oluşturuluyor...",
    currency: "Para Birimi",
    customerInformation: "Müşteri Bilgileri",
    cvc: "CVC",
    cvcPlaceholder: "CVC",
    days: "gün",
    planTrial: "DENEME",
    planMonthly: "AYLIK",
    planYearly: "YILLIK",
    planFree: "UCRETSIZ",
    planSmall: "KÜÇÜK PLAN",
    planMedium: "ORTA PLAN",
    planLarge: "BÜYÜK PLAN",
    monthly: "Aylık",
    yearly: "Yıllık",
    currentPlan: "Mevcut Plan",
    nextPlan: "Yeni Plan",
    planTransition: "Geçiş yapılıyor",
    popular: "Popüler",
    bestValue: "En İyi Değer",
    businesses: "İşletme",
    employeesPerBusiness: "İşletme başına çalışan",
    allFeatures: "Tüm Özellikler",
    basicFeatures: "Temel Özellikler",
    digitalMenuAndProducts: "Dijital Menü & Ürünler",
    unlimited: "Sınırsız",
    upgradeRequired: "Yükseltme Gerekli",
    upgradeToAccess: "Bu özelliği kullanmak için planınızı yükseltiniz",
    upgradePlan: "Planı Yükselt",
    downgradeNotAllowed:
      "Daha düşük ücretli plana geçiş desteklenmiyor. Paket düşürmek için aboneliğinizi iptal edebilirsiniz; dönem sonunda ücretsiz plana geçilir.",
    notAvailable: "Uygun değil",
    select: "Seç",
    businessLimitReached: "İşletme limitinize ulaştınız. Daha fazlası için planınızı yükseltiniz.",
    businessLimitTitle: "İşletme limitine ulaştınız.",
    businessLimitMessage: "Abonelik sayfasından daha fazla satın alabilirsiniz.",
    employeeLimitReached: "Bu işletme için çalışan limitinize ulaştınız. Daha fazlası için planınızı yükseltiniz.",
    premiumFeature: "Premium Özellik",
    moduleRequired: "Modül Gerekli",
    purchaseModuleMessage: "Bu özelliği kullanmak için bu modülü satın almanız gerekiyor",
    viewSubscriptionPage: "Abonelik Sayfasına Git",
    perMonth: "/ay",
    perYear: "/YIL",
    discount: "İndirim",
    deleteAccount: "Hesabımı Sil",
    deleteAccountDescription: "Hesabınızı silmek için telefon numaranıza gönderilecek OTP kodunu doğrulamanız gerekmektedir.",
    deleteAccountWait: "Hesabınız, aboneliğiniz bitene kadar silinmek üzere bekliyor. Tekrar aktif etmek isterseniz aşağıdaki butona tıklayınız.",
    deleteFailed: "Ürün silinemedi.",
    deleteFeedback: "Geri Bildirimi Sil",
    deleteImageFailed: "Resim silinemedi.",
    description: "Ürün açıklaması",
    disabled: "Pasif",
    duration: "Kalan Gün",
    editProduct: "Ürünü Düzenle",
    editMenu: "Menüyü Düzenle",
    editMenuProduct: "Menü Ürünlerini Düzenle",
    email: "E-posta",
    enabled: "Aktif",
    endDate: "Bitiş Tarihi",
    enterCategoryName: "Kategori adını girin",
    enterProductName: "Ürün adını girin",
    enterDescription: "Açıklama girin",
    enterDiscount: "İndirim girin",
    enterInstagramUsername: "Instagram kullanıcı adı",
    enterMenuName: "Menü adını girin",
    enterOtpCode: "Telefon numaranıza gönderilen OTP kodunu girin",
    enterPrice: "Fiyat girin",
    enterVerificationCode: "OTP kodu girin",
    error: "Hata!",
    success: "Başarılı",
    freePlanBusinessChoiceTitle: "Ücretsiz plan için işletme seçin",
    freePlanBusinessChoiceIntro:
      "Birden fazla aktif işletmeniz var. Ücretsiz planda aktif kalacak işletmeyi seçin; diğerleri pasif yapılacaktır.",
    freePlanBusinessRetentionWarning:
      "Pasif bırakılan işletmeler yaklaşık 6 ay saklanır. Süre sonunda, yükseltme ve yeniden etkinleştirme olmazsa veriler kalıcı olarak silinebilir.",
    freePlanBusinessGraceNote:
      "Süre dolana kadar seçim yapmazsanız, oluşturulma tarihine göre en eski işletme otomatik olarak aktif kalır.",
    freePlanBusinessChoiceSaved: "Seçiminiz kaydedildi.",
    noBusinessFound: "İşletme bulunamadı.",
    expireMonth: "Ay",
    expireMonthPlaceholder: "AA",
    expireYear: "Yıl",
    expireYearPlaceholder: "YY",
    failedToResendCode: "Yeni doğrulama kodu gönderilemedi!",
    failedToSendDeleteAccountEmail: "Hesap silme e-postası gönderilemedi!",
    failedToSendOtp: "OTP kodu gönderilemedi",
    feedback: "Müşteri Geri Bildirimleri",
    feedbackAndRatings: "Geri Bildirim ve Değerlendirmeler",
    feedbackDeleted: "Geri bildirim başarıyla silindi.",
    tasteRating: "Lezzet",
    serviceRating: "Hizmet",
    speedRating: "Süre",
    priceRating: "Fiyat",
    overallRating: "Genel Değerlendirme",
    totalRatings: "değerlendirme",
    ratings: "Değerlendirmeler",
    noRatings: "Henüz değerlendirme yok",
    rateExperience: "Deneyiminizi Puanlayın",
    writeComment: "Yorum yazın (isteğe bağlı)",
    atLeastOneRequired: "Lütfen en az bir puan verin veya yorum yazın",
    filter: "Filtrele",
    forbidden: "Erişim yasak. Bu işlemi gerçekleştirmek için yetkiniz bulunmuyor.",
    galleryPermissionMessage: "Uygulama resim yüklemek için galerinize erişim istiyor",
    galleryPermissionTitle: "Galeri İzni",
    generateQrCode: "QR Kod Üret",
    getProductsFailed: "Ürünler alınamadı.",
    home: "Anasayfa",
    imageDeleted: "Resim Silindi",
    imageDoesNotExist: "Resim bulunamadı!",
    imageSelectionFailed: "Resim seçimi başarısız oldu",
    invalidEmail: "Geçersiz e-posta formatı!",
    invalidName: "Geçersiz isim formatı!",
    invalidOtpCode: "Geçersiz OTP kodu",
    invalidPlanData: "Geçersiz plan verisi",
    invalidPhoneNumber: "Geçersiz telefon numarası",
    invalidVerificationCode: "Geçersiz doğrulama kodu.",
    isAvailable: "Menü Kullanıma Açık",
    isCampaign: "Kampanya",
    isProductAvailable: "Ürün Kullanıma Açık",
    isFavorite: "Favori",
    isNewItem: "Yeni Ürün",
    languageSettingsText: "Dili Değiştir",
    loading: "Yükleniyor...",
    login: "Hızlı Giriş",
    loginFailed: "Giriş başarısız. Lütfen tekrar deneyin.",
    loginSuccessful: "Giriş başarılı!",
    logout: "Çıkış Yap",
    logoutConfirmation: "Çıkış yapmak istiyor musun?",
    logoutFailed: "Çıkış yapılamadı. Lütfen tekrar deneyin.",
    logoutSuccessful: "Çıkış yapıldı!",
    menuProductDoesNotExist: "Menü ürünü bulunamadı.",
    menuProducts: "Menü Ürünleri",
    products: "Ürünler",
    stockManagement: "Stok Yönetimi",
    materialStock: "Malzeme Stoğu",
    productStock: "Ürün Stoğu",
    stockSummary: "Stok Özeti",
    lowStock: "Düşük",
    addMaterial: "Malzeme Ekle",
    editMaterial: "Malzeme Düzenle",
    materialName: "Malzeme Adı",
    enterMaterialName: "Malzeme adı girin",
    initialStock: "Başlangıç Stoğu",
    enterStockAmount: "Stok miktarı girin",
    materialCreated: "Malzeme başarıyla oluşturuldu",
    currentStock: "Mevcut Stok",
    addStock: "Stok Ekle",
    stockUpdated: "Stok güncellendi",
    stockMovements: "Stok Hareketleri",
    stockMovementIn: "Stok Girişi",
    stockMovementOut: "Stok Çıkışı",
    stockMovementAdjustment: "Düzeltme",
    stockMovementInitialNote: "Başlangıç stoku",
    stockMovementAddedNote: "Stok eklendi",
    stockMovementOrderDeduction: "Sipariş düşümü: {product}",
    noMovementsFound: "Henüz hareket yok",
    noMaterialsFound: "Malzeme bulunamadı",
    createNewMaterial: "Yeni Malzeme Oluştur",
    incompatibleMeasurementUnit: "Kullanım birimi, malzeme stok birimi ile uyumlu olmalıdır (ör. kg-g, litre-ml).",
    compatibleUnitsHint: "Stok birimi: {unit}. Yalnızca uyumlu birimler seçilebilir.",
    noProductStockFound: "Stok takibi yapılan ürün bulunamadı",
    stockAlertSettings: "Stok Uyarı Ayarları",
    materialThreshold: "Malzeme Uyarı Eşiği (%)",
    productThreshold: "Ürün Uyarı Eşiği (%)",
    alertEmail: "Uyarı E-posta Adresi",
    alertsActive: "Uyarılar Aktif",
    settingsSaved: "Ayarlar kaydedildi",
    stockInfo: "Stok Bilgisi",
    stockModuleRequired: "Stok Modülü Gerekli",
    stockModuleRequiredMessage: "Stok özelliklerini kullanmak için Stok Yönetimi modülünü satın alın.",
    stockInfoTooltip: "Ürün adedini ve üretimde kullanılan malzemeleri bu alandan belirleyebilirsiniz. Sipariş tamamlandığında stok otomatik düşülür.",
    productQuantity: "Ürün Adedi",
    trackStock: "Stok Takibi",
    productStockQuantity: "Ürün adedi (opsiyonel)",
    materialInfo: "Malzeme Bilgisi",
    selectMaterial: "Malzeme Seç",
    notSpecified: "Belirtilmemiş",
    lastUpdated: "Son güncelleme",
    pieces: "adet",
    materials: "Malzemeler",
    pleaseCreateMenuFirst: "Lütfen önce bir menü oluşturun.",
    menuDoesNotExist: "Menü bulunamadı.",
    menuImage: "İşletme Logosu",
    menuLimitError: "Maksimum menü limitine ulaştınız",
    menuName: "Menü Adı",
    menuCreated: "Menü başarıyla oluşturuldu",
    menuUpdated: "Menü başarıyla düzenlendi",
    menuNotFound: "Menü bulunamadı.",
    menuSubtitle: "Bu işletmeye ait menü bulunamadı",
    menuTheme: "Menü Teması",
    name: "Ad",
    networkErrorBody: "Bir ağ hatası oluştu. Lütfen internet bağlantınızı kontrol edin ve tekrar deneyin.",
    networkErrorTitle: "Ağ Hatası",
    noInternetConnection: "İnternet bağlantınız yok. Lütfen bağlantınızı kontrol edip tekrar deneyin.",
    connectionTimeout: "Bağlantı zaman aşımına uğradı. Lütfen internet bağlantınızı kontrol edip tekrar deneyin.",
    no: "Hayır",
    noFeedbacks: "Hiç geri bildirim yok.",
    noPlansFound: "Plan bulunamadı. Lütfen bağlantınızı kontrol edin veya daha sonra tekrar deneyin.",
    noResponse: "Sunucudan yanıt alınamıyor. Lütfen internet bağlantınızı kontrol edin.",
    noResultsFound: "Arama kriterlerinize uygun sonuç bulunamadı",
    noSubscription: "Abonelik bulunamadı",
    noSubscriptionTitle: "Henüz bir aboneliğiniz yok",
    noSubscriptionMessage: "Tüm özelliklerin kilidini açmak ve işletmenizi yönetmeye başlamak için bir plan seçin.",
    explorePlans: "Planları Keşfet",
    notAdded: "Eklenmedi",
    ok: "Tamam",
    otpCodeSent: "OTP kodu gönderildi",
    otpVerification: "OTP Doğrulama",
    passwordRequirements: "Şifre 8-16 karakter uzunluğunda olmalıdır.",
    permissionDenied: "QR kodu kaydetmek için izin reddedildi",
    phoneNumber: "Telefon Numarası",
    pleaseEnterValidPhoneNumber: "Lütfen geçerli bir telefon numarası girin",
    pleaseAddProduct: "Bu menüye ait ürün bulunamadı",
    pleaseFillAllFields: "Lütfen zorunlu tüm alanları doldurun",
    price: "Fiyat",
    processing: "İşleniyor...",
    profile: "Profil",
    userName: "Kullanıcı Adı",
    businessName: "İşletme Adı",
    enterBusinessName: "İşletme adını girin",
    businessNameTooltip: "Bu işletme adı menülerinizde görünecektir.",
    profileUpdated: "Profil başarıyla güncellendi",
    completeProfile: "Profilinizi Tamamlayın",
    welcomeToKuar: "Kuar'a Hoş Geldiniz!",
    completeProfileMessage: "Başlamak için lütfen profil bilgilerinizi tamamlayın.",
    enterAddress: "İşletme adresinizi girin",
    address: "Adres",
    emailAlreadyExists: "Bu e-posta adresi zaten kullanılıyor",
    qrCode: "QR Kod",
    qrCodeSaved: "QR kod galeriye kaydedildi",
    qrGenerationFailed: "QR kod oluşturulamadı",
    saveFailed: "QR kod kaydedilemedi",
    saveToGallery: "Galeriye Kaydet",
    searchByName: "İsme göre ara...",
    selectCategory: "Kategori Seçin (zorunlu)",
    selectMenuTheme: "Menü Teması Seçiniz",
    serverError: "Sunucu hatası oluştu. Lütfen daha sonra tekrar deneyin.",
    sessionInvalidBody: "Oturumunuz sonlandırıldı. Lütfen tekrar giriş yapın.",
    sessionInvalidTitle: "Oturum Sonlandırıldı",
    settings: "Ayarlar",
    socialMedia: "Instagram Kullanıcı Adı",
    startDate: "Başlangıç Tarihi",
    status: "Durum",
    storagePermissionMessage: "Uygulama resim yüklemek için depolama alanınıza erişim istiyor",
    storagePermissionTitle: "Depolama İzni",
    subscribe: "Satın Al",
    subscription: "Aboneliğim",
    subscriptionCancelled: "Abonelik başarıyla iptal edildi!",
    subscriptionPendingMessage: "Yeni planınız mevcut planınızın süresi bittiğinde aktif olacaktır.",
    subscriptionCancelledMessage: "*Abonelik süreniz bittikten sonra tekrar abonelik satın alabilirsiniz.",
    subscriptionCreated: "Abonelik başarıyla oluşturuldu!",
    subscriptionAlreadyExists: "Zaten aktif bir aboneliğiniz var.",
    subscriptionDetails: "Abonelik Detayları",
    subscriptionExpired: "Abonelik Sonlandı",
    subscriptionFailed: "Abonelik oluşturulamadı. Lütfen tekrar deneyiniz.",
    subscriptionChangeError: "Abonelik değiştirilemedi. Tekrar deneyiniz.",
    subscriptionPrice: "Abonelik Fiyatı",
    subscriptionNotFound: "Abonelik bulunamadı. Lütfen tekrar deneyiniz.",
    surname: "Soyad",
    phone: "Telefon Numarası",
    phonePlaceholder: "+90 5XX XXX XX XX",
    themeSettingsText: "Temayı değiştir",
    tooManyFailedAttempts: "Çok fazla başarısız deneme. 5 dakika sonra tekrar deneyin.",
    trialDescription: "Deneme planını seçtiğinizde, 7 günlük deneme süreniz başlayacak ve tüm işlemlerinizin ücretsiz olarak devam edecektir.",
    monthlyDescription: "Aylık plan ile her ay ödeme yaparak hizmetimizi kullanabilirsiniz.",
    yearlyDescription: "Yıllık plan ile bir kere ödeyip hem tasarruf edip hem de yıl boyunca hizmetimizi kullanabilirsiniz.",
    unableToConnectToServer: "Sunucuya bağlanılamadı. Lütfen internet bağlantınızı kontrol edin.",
    unauthorized: "Yetkisiz erişim. Lütfen tekrar giriş yapın.",
    unexpectedErrorOccurred: "Bilinmeyen bir hata oluştu. Lütfen daha sonra tekrar deneyin.",
    usage: "Kullanım",
    unsupportedFormat: "Sunucu desteklenmeyen bir format döndürdü. Lütfen tekrar deneyin.",
    update: "Kaydet",
    save: "Kaydet",
    updateFailed: "Ürün güncellenemedi.",
    updating: "Kaydediliyor...",
    uploadFailed: "Resim yüklenemedi.",
    uploadImage: "Resim Yükle",
    userAccountIsNotActivated: "Kullanıcı hesabı aktif edilmedi.",
    userDoesNotExist: "Kullanıcı bulunamadı!",
    yes: "Evet",
    zipcode: "Posta Kodu",
    deleteAccountWarning: "Hesabınızı silmek için telefon numaranıza gönderilecek OTP kodunu doğrulamanız gerekmektedir.",
    resendCode: "Yeni kod gönder",
    // Subscription status translations
    statusActive: "AKTİF",
    statusPending: "BEKLEMEDE",
    statusCanceled: "İPTAL EDİLDİ",
    statusChanged: "DEĞİŞTİRİLDİ",
    statusUnpaid: "ÖDEME BAŞARISIZ",
    statusTrial: "ÜCRETSİZ DENEME",
    statusExpired: "SÜRESİ DOLDU",
    statusFailed: "BAŞARISIZ",
    type: "Tür",
    subscriptionTypeNEW: "Yeni abonelik",
    subscriptionTypeUPGRADE: "Yükseltme",
    subscriptionTypeDOWNGRADE: "Düşürme",
    retryPayment: "Kart Güncelle ve Ödemeyi Tekrarla",
    retryPaymentDescription: "Başarısız ödemeyi tekrarlamak için yeni kart bilgilerinizi girin.",
    paymentRetrySuccess: "Ödeme tekrarlandı. Aboneliğiniz kısa sürede aktif edilecektir.",
    cancelPendingChange: "Plan Değişikliğini İptal Et",
    confirmCancelPendingChange: "Bekleyen plan değişikliğini iptal etmek istediğinize emin misiniz? Mevcut planınız aktif kalacaktır.",
    pendingChangeCancelled: "Plan değişikliği başarıyla iptal edildi.",
    paymentDetails: "Ödeme Detayları",
    paymentFailed: "Ödeme işlemi başarısız",
    paymentProcessingMessage: "Ödeme işleminiz tamamlanıyor...",
    paymentProcessingTimeout: "Ödemeniz işleniyor. Aboneliğiniz kısa sürede güncellenecektir.",
    paymentHistory: "Ödeme Geçmişi",
    paymentHistoryDescription: "Abonelik değişiklik geçmişiniz.",
    noPaymentHistory: "Ödeme geçmişi bulunamadı.",
    paymentMethodChoiceTitle: "Ödeme yöntemi",
    useSavedCard: "Kayıtlı kartımı kullan",
    savedCardHint: "Ödeme altyapısında kayıtlı kartınız kullanılır; kart bilgisi girmeniz gerekmez.",
    useNewCardInstead: "Farklı kart girmek istiyorum",
    savedPaymentMethodTitle: "Kayıtlı kartım",
    savedPaymentMethodDescription: "Yenilemeler ödeme altyapısındaki kayıtlı kartınızla yapılır.",
    updateCardButton: "Kartı güncelle",
    cardUpdateTitle: "Kart güncelleme",
    cardUpdateLoadError: "Kart güncelleme başlatılamadı. Lütfen tekrar deneyin.",
    cardUpdateSuccess: "Kart güncellendi.",
    cardUpdateOpenedExternally: "Kart güncelleme sayfası tarayıcıda açıldı. İşlemi bitirdikten sonra uygulamaya dönün.",
    cardInformation: "Kart Bilgileri",
    addressInformation: "Fatura Adresi",
    billingInfoTitle: "Fatura bilgileri",
    billingInfoHint: "Abonelik ödemesi ve faturalar için kullanılır.",
    billingInfoUpdated: "Fatura bilgileri kaydedildi",
    zipPostalCode: "Posta kodu",
    menuFooterText: "Kocaeli'de sevgiyle yapıldı ❤️",
    // Tooltip texts
    menuImageTooltip: "Bu alanda yükleyeceğiniz logo menülerinizde gözükecektir.",
    menuNameTooltip: "Menünüze vermek istediğiniz ismi bu alana yazabilirsiniz.",
    currencyTooltip: "Menünüzde ürün fiyatlarının yanında gösterilecek para birimini seçebilirsiniz.",
    menuThemeTooltip: "Menünüzün görünümünü değiştirmek için farklı temalar arasından seçim yapabilirsiniz.",
    instagramTooltip: "Buraya girdiğiniz Instagram kullanıcı adı menünüzde görünecektir. Müşteriler üzerine dokunarak sayfanızı ziyaret edebilir.",
    productImageTooltip: "Ürününüzün fotoğrafını buradan yükleyebilirsiniz.",
    productNameTooltip: "Ürününüzün adını bu alana yazabilirsiniz.",
    descriptionTooltip: "Ürününüz hakkında detaylı açıklama yazabilirsiniz.",
    categoryTooltip: "Ürününüzün hangi kategoriye ait olduğunu seçebilirsiniz.",
    allergensTooltip: "Ürününüzde bulunan alerjenleri işaretleyebilirsiniz.",
    discountTooltip: "Ürününüze uygulamak istediğiniz indirim oranını girebilirsiniz (0-100 arası).",
    priceTooltip: "Ürününüzün satış fiyatını girebilirsiniz.",
    // Image Selection Modal
    selectImage: "Resim Seç",
    selectOrUploadImage: "Resim Seç veya Yükle",
    stockImages: "Hazır Resimler",
    gallery: "Galeri",
    searchImages: "Resim ara... (örn: pizza, kahve)",
    searchForImages: "Resim aramak için yukarıdaki arama kutusunu kullanın",
    poweredByPixabay: "Ücretsiz resimler Pixabay tarafından sağlanmaktadır",
    enterSearchQuery: "Lütfen bir arama metni girin",
    noImagesFound: "Resim bulunamadı",
    imageSearchFailed: "Resim arama başarısız",
    imageSelected: "Resim seçildi",
    imageDownloadFailed: "Resim indirilemedi",
    selectFromGallery: "Cihazınızdan resim seçmek için aşağıdaki butona tıklayın",
    openGallery: "Galeriyi Aç",
    pixabayCredit: "Ücretsiz resimler",
    searchingImages: "Resimler aranıyor...",
    info: "Bilgi",
    required: "zorunlu",
    optional: "opsiyonel",
    // Email/Password Authentication
    loginWithEmail: "E-posta ile Giriş Yap",
    emailPlaceholder: "E-posta adresinizi girin",
    passwordPlaceholder: "Şifrenizi girin",
    confirmPasswordPlaceholder: "Şifrenizi tekrar girin",
    noAccountYet: "Henüz hesabınız yok mu?",
    signUp: "Kayıt Ol",
    alreadyHaveAccount: "Zaten hesabınız var mı?",
    signIn: "Giriş Yap",
    register: "Kayıt Ol",
    registering: "Kayıt oluşturuluyor...",
    namePlaceholder: "Adınızı girin",
    registerSuccess: "Kayıt başarılı! Aktivasyon kodu için e-postanızı kontrol edin.",
    activateAccount: "Hesabı Aktifleştir",
    activationCodeSent: "E-posta adresinize 6 haneli aktivasyon kodu gönderildi.",
    enterActivationCode: "6 haneli aktivasyon kodunu girin",
    activating: "Aktifleştiriliyor...",
    activate: "Aktifleştir",
    resendActivationCode: "Aktivasyon Kodunu Tekrar Gönder",
    activationSuccess: "Hesabınız başarıyla aktifleştirildi!",
    passwordsDoNotMatch: "Şifreler eşleşmiyor",
    passwordTooShort: "Şifre 8-16 karakter olmalıdır",
    invalidEmailFormat: "Geçerli bir e-posta adresi girin",
    nameRequired: "İsim gerekli",
    orContinueWith: "veya şununla devam et",
    loginWithGoogle: "Google ile Giriş Yap",
    loginWithApple: "Apple ile Giriş Yap",
    // Suggestion feature
    suggestions: "Öneri ve Görüş",
    suggestionsPlaceholder: "Öneri ve görüşlerinizi bizimle paylaşın...",
    submitSuggestion: "Gönder",
    suggestionSent: "Teşekkürler! Öneriniz başarıyla gönderildi.",
    suggestionFailed: "Öneri gönderilemedi. Lütfen tekrar deneyin.",
    enterSuggestion: "Lütfen önerinizi girin",
    // Employee Management
    myEmployees: "Çalışanlarım",
    employeeLogin: "Çalışan Girişi",
    employeeLoginTitle: "Çalışan Girişi",
    accessCode: "Erişim Kodu",
    accessCodePlaceholder: "XXXX-XXXX-XXXX",
    invalidAccessCode: "Geçersiz erişim kodu formatı",
    ownerLogin: "İşletme Sahibi Olarak Giriş Yap",
    addEmployee: "Çalışan Ekle",
    editEmployee: "Çalışan Düzenle",
    saveChanges: "Kaydet",
    employeeUpdated: "Çalışan güncellendi. Erişim kodu değişmedi.",
    employeeUpdateFailed: "Çalışan güncellenemedi.",
    employeeName: "Çalışan Adı",
    employeePhone: "Telefon Numarası",
    employeeRole: "Rol",
    employeeAdded: "Çalışan başarıyla eklendi",
    employeeDeleted: "Çalışan başarıyla silindi",
    noEmployeesFound: "Çalışan bulunamadı. İlk çalışanınızı ekleyin!",
    regenerateCode: "Kodu Yenile",
    confirmRegenerateCode: "Erişim kodunu yenilemek istediğinizden emin misiniz? Eski kod artık çalışmayacak.",
    codeCopied: "Yeni erişim kodu",
    deleteEmployee: "Çalışanı Sil",
    confirmDeleteEmployee: "Bu çalışanı silmek istiyor musunuz?",
    roleOwner: "Sahip",
    roleManager: "Yönetici",
    roleWaiter: "Garson",
    roleChef: "Şef",
    roleCashier: "Kasiyer",
    selectRole: "Rol Seçin",
    businessLogin: "İşletme Girişi",
    employeeLoginInfo: "Çalışan olarak giriş yapmak için işvereninizden erişim kodunu isteyin.",
    // Table & Order Management
    tableManagement: "Masa Yönetimi",
    tableAreas: "Masa Alanları",
    tables: "Masalar",
    addArea: "Alan Ekle",
    addTableArea: "Alan Ekle",
    editArea: "Alan Düzenle",
    addTable: "Masa Ekle",
    tableAddModeSingle: "Tekli",
    tableAddModeBulk: "Toplu",
    tableBulkPrefix: "Önek",
    tableBulkCount: "Masa sayısı",
    enterTableBulkPrefix: "örn. ABC, VIP",
    enterTableBulkCount: "örn. 10",
    tableBulkInvalidCount: "1 ile 100 arasında tam sayı girin.",
    tableBulkPrefixRequired: "Masa adları için önek girin.",
    tableBulkPreview: "{{p}}-{{start}} … {{p}}-{{end}}",
    tablesBulkCreatedAll: "{{count}} masa oluşturuldu.",
    tablesBulkPartial: "{{ok}} oluşturuldu, {{fail}} oluşturulamadı.",
    areaName: "Alan Adı",
    tableNumber: "Masa Numarası",
    capacity: "Kapasite",
    enterAreaName: "Alan adını girin",
    enterTableNumber: "örn. 1, A1, VIP-1",
    table: "Masa",
    statusAvailable: "Müsait",
    statusOccupied: "Dolu",
    statusReserved: "Masa Rezerveli",
    statusCleaning: "Temizleniyor",
    noAreasFound: "Alan bulunamadı. İlk alanınızı ekleyin!",
    noTablesFound: "Masa bulunamadı",
    areaCreated: "Alan başarıyla oluşturuldu",
    areaDeleted: "Alan başarıyla silindi",
    tableCreated: "Masa başarıyla oluşturuldu",
    tableDeleted: "Masa başarıyla silindi",
    confirmDeleteArea: "Bu alanı silmek istiyor musunuz?",
    confirmDeleteTable: "Bu masayı silmek istiyor musunuz?",
    deleteTableFailed: "Masa silinemedi.",
    deleteAreaFailed: "Alan silinemedi.",
    editModeHint: "Her masanın altındaki düzenle veya sil ile işlem yapın. Bitince tik işaretine dokunun.",
    areaEditModeHint: "Her alanın altındaki düzenle veya sil ile işlem yapın. Bitince tik işaretine dokunun.",
    tableCardEdit: "Düzenle",
    tableCardDelete: "Sil",
    editTable: "Masayı Düzenle",
    // Orders
    orders: "Siparişler",
    order: "Sipariş",
    orderNumber: "Sipariş Numarası",
    noActiveOrder: "Aktif sipariş yok",
    noItemsInOrder: "Siparişte ürün yok",
    addProducts: "Ürün Ekle",
    addMore: "Daha Ekle",
    selectProducts: "Ürün Seçin",
    searchProducts: "Ürün ara...",
    noProductsFound: "Ürün bulunamadı",
    add: "Ekle",
    items: "ürün",
    confirmAndAdd: "Onayla ve Ekle",
    cartEmpty: "Sepet boş",
    itemsAddedToOrder: "Ürünler siparişe eklendi",
    itemRemoved: "Ürün silindi",
    orderUpdated: "Sipariş güncellendi",
    orderCancelled: "Sipariş iptal edildi",
    confirmCancelOrder: "Bu siparişi iptal etmek istiyor musunuz?",
    cancelOrderWarning: "Bu işlem geri alınamaz",
    completeOrder: "Tamamla",
    waiter: "Garson",
    total: "Toplam",
    pending: "Bekliyor",
    preparing: "Hazırlanıyor",
    ready: "Hazır",
    delivered: "Teslim Edildi",
    cancelled: "İptal Edildi",
    deliverSelected: "Teslim Et",
    deliverOrder: "Siparişi teslim et",
    deliverPickQty: "Hazır ürünleri teslimata dahil etmek için satırlarda + ile adet seçin.",
    deliverPickQtyNoKitchen: "Teslim için satırlarda + ile adet seçin.",
    itemsDelivered: "Teslim edildi",
    // Kitchen Display
    kitchenDisplay: "Mutfak Ekranı",
    activeOrders: "Aktif Siparişler",
    pendingItems: "Bekleyen Ürünler",
    noKitchenOrders: "Hazırlanacak sipariş yok",
    kitchenRelaxMessage: "Mola verin, mutfak boş!",
    startPreparing: "Başla",
    markReady: "Hazır",
    itemUpdated: "Ürün güncellendi",
    // Cashier & Payments
    cashier: "Kasa",
    cash: "Nakit",
    creditCard: "Kredi Kartı",
    mealCard: "Yemek Kartı",
    mobilePayment: "Mobil Ödeme",
    paid: "Ödendi",
    remaining: "Kalan",
    payAll: "Tümünü Öde",
    paySelected: "Seçilenleri Öde",
    paymentMethod: "Ödeme Yöntemi",
    paymentCompleted: "Ödeme tamamlandı",
    confirmPayment: "Ödemeyi Onayla",
    closeOrder: "Hesabı Kapat",
    closeFailed: "Hesap kapatılamadı",
    refundFailed: "İade başarısız",
    selectItemsToPay: "Lütfen ödeme yapılacak ürünleri seçin",
    itemSelected: "ürün seçildi",
    tableNotAvailableForCashier: "Bu masa kasa için şu an kullanılamıyor",
    useReservationModuleForReservations: "Masa rezervasyonları için Rezervasyon menüsünü kullanın.",
    tableOccupiedForReservation: "Bu masa dolu; rezervasyon yalnızca müsait veya rezerveli masalar için yapılabilir.",
    reservations: "Rezervasyon",
    reserveTableTitle: "Masayı rezerve et",
    reservationNote: "Rezervasyon notu",
    reservationNotePlaceholder: "örn. akşam 7, 4 kişi, X kişisi adına",
    reserveTable: "Rezerve et",
    clearReservation: "Rezervasyonu kaldır",
    updateReservationNote: "Notu güncelle",
    reservationNoteRequired: "Lütfen rezervasyon notu girin",
    reservationUpdated: "Rezervasyon kaydedildi",
    reservationCleared: "Rezervasyon kaldırıldı",
    closeOrderConfirmation: "Bu hesabı kapatmak istediğinize emin misiniz? Masa müsait olarak ayarlanacak.",
    payBeforeCloseHint: "Önce ödemeyi alın, ardından hesabı kapatabilirsiniz.",
    goToCashier: "Ödeme / Hesabı Kapat",
    selectAll: "Tümünü Seç",
    confirm: "Onayla",
    fetchFailed: "Veri alınamadı",
    // Business related
    createBusiness: "İşletme Oluştur",
    businessDescription: "Açıklama",
    businessCreated: "İşletme başarıyla oluşturuldu",
    businessUpdated: "İşletme başarıyla güncellendi",
    editBusinessTitle: "İşletmeyi düzenle",
    businessDeleted: "İşletme başarıyla silindi",
    businessDeletionDangerZone: "Tehlikeli bölge",
    businessDeletionTitle: "İşletmeyi kalıcı olarak sil",
    businessDeletionWarning: "Bu işlem işletmeyi ve ilişkili tüm verileri (menüler, siparişler, masalar, çalışanlar, raporlar) kalıcı olarak siler. Geri alınamaz.",
    businessDeletionSendCode: "E-postaya doğrulama kodu gönder",
    businessDeletionCodeLabel: "E-postadaki 6 haneli kod",
    businessDeletionCodeSent: "Doğrulama kodu e-postanıza gönderildi.",
    businessDeletionConfirmDelete: "Kalıcı olarak sil",
    businessDeletionFailed: "İşlem tamamlanamadı.",
    businessNameRequired: "İşletme adı zorunludur",
    enterBusinessDescription: "Açıklama girin (isteğe bağlı)",
    noBusinesses: "Henüz bir işletmeniz bulunmuyor.",
    createFirstBusiness: "Başlamak için ilk işletmenizi oluşturun.",
    customerFeedback: "Müşteri Geri Bildirimleri",
    digitalMenu: "Dijital Menü",
    noDigitalMenus: "Henüz dijital menü yok",
    digitalMenuLimitReached: "Bu işletme için zaten bir dijital menü oluşturulmuş. Her işletme sadece 1 dijital menü oluşturabilir.",
    // Dashboard & Reports
    dashboard: "Dashboard",
    reports: "Raporlar",
    revenue: "Ciro",
    totalOrders: "Sipariş",
    totalItems: "Satılan Ürün",
    averageOrder: "Ort. Sipariş",
    last7Days: "Son 7 Gün",
    topProducts: "En Çok Satanlar",
    paymentDistribution: "Ödeme Dağılımı",
    today: "Bugün",
    thisWeek: "Bu Hafta",
    thisMonth: "Bu Ay",
    noReportData: "Veri bulunamadı",
    soldItems: "satıldı",
    mixed: "Karma",
    detailedReport: "Detaylı Rapor",
    downloadReport: "Rapor İndir",
    reportDescription: "Grafikli detaylı HTML rapor",
    last3Months: "Son 3 Ay",
    last6Months: "Son 6 Ay",
    shareReport: "Raporu Paylaş",
    reportReady: "Raporunuz Hazır",
    reportGenerating: "Rapor oluşturuluyor...",
    // Permissions
    permissions: "Yetkiler",
    permissionsDescription: "Bu çalışanın erişebileceği özellikleri seçin.",
    permDigitalMenu: "Dijital Menü",
    permProducts: "Ürünler",
    permEmployees: "Çalışanlar",
    permTableManagement: "Masa Yönetimi",
    permKitchenDisplay: "Mutfak Ekranı",
    permCashier: "Kasa",
    permReservation: "Rezervasyon",
    permFeedback: "Müşteri Geri Bildirimleri",
    permDashboard: "Dashboard",
    defaultPermissions: "Bu rol için varsayılan yetkiler",
    // Module Subscription
    freeTrialActive: "Ücretsiz Deneme Aktif",
    dayRemaining: "gün kaldı",
    daysRemaining: "gün kaldı",
    recommended: "Önerilen",
    basicBundle: "Temel Paket",
    alreadyOwned: "Sahipsin",
    applyBundle: "Paketi Uygula",
    owned: "Sahip",
    proRated: "Orantılı",
    yearlyReference: "Yıllık",
    proRatedForDays: "Kalan {days} gün için",
    proRatedUntilDate: "{date} tarihine kadar",
    proRatedForRemainingPeriod: "Kalan dönem için",
    proRatedBillingNote:
      "Yeni modüller, mevcut aboneliğinizin bitiş tarihine ({date}) kadar orantılı fiyatlandırılır. Üstü çizili fiyatlar tam yıllık ücrettir.",
    proRatedCartNote:
      "Toplam, yıllık değil; mevcut abonelik döneminizin kalan süresine göre hesaplanmıştır.",
    annualModulePrices: "Gösterilen fiyatlar yıllık ücrettir.",
    availableModules: "Mevcut Modüller",
    noModulesAvailable: "Mevcut modül yok.",
    allModulesOwned: "Tüm modüllerin kilidini açtınız.",
    moduleSelected: "modül seçildi",
    modulesSelected: "modül seçildi",
    clear: "Temizle",
    subtotal: "Ara Toplam",
    bundleDiscount: "Paket İndirimi",
    proceedToPayment: "Ödemeye Geç",
    payNow: "Şimdi Öde",
    selectModulesTitle: "Modül seçin",
    selectModulesMessage: "Devam etmek için en az bir modül seçiniz.",
    modulesPurchased: "Modüller başarıyla satın alındı.",
    currentSubscription: "Mevcut Abonelik",
    subscriptionEndDate: "Bitiş tarihi",
    bundleAlreadyOwned: "Pakete zaten sahipsiniz",
    bundleAlreadyOwnedMessage: "Bu paketteki tüm modüllere zaten sahipsiniz.",
    fetchError: "Veri yüklenemedi.",
    businessCount: "İşletme sayısı",
    free: "Ücretsiz",
    firstBusinessFree: "1. işletme ücretsiz",
    businessLimitReachedModule: "İşletme limitinize ulaştınız. Abonelik sayfasından daha fazla satın alabilirsiniz.",
    selectBusinessModuleFirst: "Lütfen önce İşletme modülünü seçin (1 ücretsiz işletme dahil).",
    subscriptionExpiresTomorrow: "Aboneliğiniz yarın sona eriyor!",
    subscriptionExpiresIn: "Abonelik bitimine",
    renewToKeepAccess: "Modüllerinize erişimi sürdürmek için yenileyin.",
    trialDaysLeft: "Ücretsiz deneme:",
    trialAllModulesAccess: "Deneme süresince tüm modüllere erişiminiz var.",
    emailNotFound: "E-posta bulunamadı",
    // Module names and descriptions
    moduleCreateBusiness: "İşletme Oluştur",
    moduleCreateBusinessDesc: "İşletme profilinizi oluşturun ve yönetin",
    moduleDigitalMenu: "Dijital Menü",
    moduleDigitalMenuDesc: "QR kodlu dijital menüler oluşturun ve yönetin",
    moduleProductManagement: "Ürün Yönetimi",
    moduleProductManagementDesc: "Ürünleri, kategorileri ve envanteri yönetin",
    moduleEmployeeManagement: "Çalışan Yönetimi",
    moduleEmployeeManagementDesc: "Çalışanları, rolleri ve yetkileri yönetin",
    moduleTableManagement: "Masa Yönetimi",
    moduleTableManagementDesc: "Masaları, alanları ve oturma düzenini yönetin",
    moduleCashRegister: "Kasa",
    moduleCashRegisterDesc: "Ödemeleri işleyin ve işlemleri yönetin",
    moduleKitchenDisplay: "Mutfak Ekranı",
    moduleKitchenDisplayDesc: "Mutfak sipariş yönetimi ve hazırlık takibi",
    moduleReservations: "Rezervasyon",
    moduleReservationsDesc: "Masa rezervasyonlarını ve rezervasyonları yönetin",
    moduleFeedback: "Müşteri Geri Bildirimleri",
    moduleFeedbackDesc: "Müşteri geri bildirimlerini toplayın ve yönetin",
    moduleDashboard: "Dashboard",
    moduleDashboardDesc: "Raporları, analizleri ve iş öngörülerini görüntüleyin",
    bundleBasicName: "Temel Paket",
    bundleBasicDesc: "Başlamak için ihtiyacınız olan her şey",
    // Web shell & shared UI
    back: "Geri",
    delete: "Sil",
    new: "Yeni",
    theme: "Tema",
    lightMode: "Açık",
    darkMode: "Koyu",
    selectLanguage: "Dil seçin",
    language: "Dil",
    connected: "Canlı",
    disconnected: "Çevrimdışı",
    itemReady: "Ürün hazır",
    cancelItem: "Ürünü iptal et",
    search: "Ara",
    cancelOrder: "Siparişi iptal et",
    orderSent: "Sipariş gönderildi",
    sendOrder: "Siparişi gönder",
    createTable: "Masa oluştur",
    noOrders: "Aktif sipariş yok",
    business: "İşletme",
    welcome: "Hoş geldiniz",
    openMenu: "Menüyü aç",
    expandSidebar: "Kenar çubuğunu genişlet",
    collapseSidebar: "Kenar çubuğunu daralt",
    pageNotFound: "Sayfa bulunamadı",
    pageNotFoundDescription:
      "Aradığınız sayfa taşınmış, silinmiş ya da hiç var olmamış olabilir.",
    homePage: "Ana Sayfa",
    goToDashboard: "Panele Git",
    noFeedback: "Henüz geri bildirim yok",
    unexpectedErrorTitle: "Bir şeyler ters gitti",
    unexpectedErrorDescription:
      "Beklenmedik bir hata oluştu. Lütfen tekrar deneyin. Sorun devam ederse destek ile iletişime geçin.",
    errorCode: "Hata kodu",
    tryAgain: "Tekrar dene",
    share: "Paylaş",
    copy: "Kopyala",
    regenerateAccessCode: "Kodu yenile",
    accessCodeRegenerated: "Erişim kodu yenilendi",
    noEmployees: "Henüz çalışan yok",
    addItem: "Ürün ekle",
    noTablesYet: "Henüz masa yok",
    tablePrefix: "Önek",
    capacityLabel: "Kapasite",
    count: "Adet",
    tableStatusEmpty: "Boş",
    tableStatusOccupied: "Dolu",
    tableStatusReserved: "Rezerve",
    menu: "Menü",
    password: "Şifre",
    forgotPassword: "Şifremi unuttum",
    loginSubtitle: "İşletme veya çalışan hesabınla devam et",
    showPassword: "Şifreyi göster",
    hidePassword: "Şifreyi gizle",
    footerTagline:
      "Restoran ve kafe işletmeleri için modern yönetim platformu. Dijital menü, sipariş, mutfak ve kasa — hepsi tek yerde.",
    footerProduct: "Ürün",
    footerFeatures: "Özellikler",
    footerLegal: "Yasal",
    footerPrivacy: "Gizlilik",
    footerTerms: "Kullanım Şartları",
    footerContact: "İletişim",
    footerCopyright: "Tüm hakları saklıdır.",
    footerMadeWith: "Kocaeli'de sevgiyle yapıldı",
    registerSubtitle: "İşletmeni Kuar ile yönetmeye başla",
  },
};
